server:
  port: 9000
eureka:
  instance:
    # 主机名（域名）
    hostname: localhost
    # 提供给注册中心 true： hostname false：ip （默认false，提供给注册中心的是当前hostname，服务调用方会按hostname调用服务，true则按ip调用）
    prefer-ip-address: true
    # 实例id（一个service下可能有多个实例提供相同服务，在相同的服务下此id需要唯一。默认按 系统用户名+hostname+port）
    instance-id: heiheihei
  client:
    # 单节点下面两个配置不需要启用
    # 本机不注册到注册中心（自己就是注册中心，不需要注册自己）
    register-with-eureka: false
    # 自己就是注册中心，不需要检索注册中心的服务。若改为true。服务启动时检索注册中心服务（向自己检索）会报错（原因是服务器本身作为注册中心此时还没有启动完成）
    # 启动顺序：拉取服务 -> 启动完成 -> 注册服务
    # endpoint=DefaultEndpoint{ serviceUrl='http://127.0.0.1:9000/eureka/}, exception=java.net.ConnectException: Connection refused: connect stacktrace=com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
    fetch-registry: false
    # 把自己当成注册方。下面的配置为注册中心地址，eureka会往此地址的注册中心注册服务，拉取服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/