server:
  port: 9002
eureka:
  instance:
    # 主机名（域名）
    hostname: localhost
    # 提供给注册中心 true： hostname false：ip （默认false，提供给注册中心的是当前hostname，服务调用方会按hostname调用服务，true则按ip调用）
    prefer-ip-address: true
    # 实例id（一个service下可能有多个实例提供相同服务，在相同的服务下此id需要唯一。默认按 系统用户名+hostname+port）
    instance-id: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
