server:
  port: 7000
spring:
  application:
    name: server-consumer
eureka:
  client:
    # 这里消费端只消费，不注册
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/